name: A workflow for my Hello World file
on: push

jobs:

  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello!"

  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"