name: A workflow for my Hello World file
on: push
inputs:
  name:
    description: 'Person to greet'
    required: true
    default: 'welcome'
  home:
    description: 'location'
    required: false
    default: 'vanalex'

jobs:

  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello!"
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"

  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"