name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x echo.shs
        shell: bash